# -*- coding: utf-8 -*-
"""3ds-cd-regressao-linear-GABARITO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rB-ZnEtKSRTtlAsqv9o2bYwyzaxAc6iZ

>📘 <b>AULA - REGRESSÃO LINEAR COM PYTHON  
>Curso: Técnico em Desenvolvimento de Sistemas  
>Turma: 3DS  
>Disciplina: Ciência de Dados  
>Conteúdo: Regressão Linear com Statsmodels e Scikit-Learn </b>
>
><img src='https://i.postimg.cc/GhjJfhHb/linear-regression.png' width=880 height=388>

>### ⚠️ SALVE UMA CÓPIA DO NOTEBOOK NO SEU DRIVE, ANTES DE EXECUTAR OS CÓDIGOS!  
>### ⚠️ RENOMEIE O ARQUIVO INCLUINDO O SEU NOME PARA, POR EX., FICAR ASSIM,:  
<b>carla-3ds-cd-regressao-linear.ipynb</b>.

>### 🧠 <b>INTRODUÇÃO: O que é Regressão Linear?</b>  

A regressão linear é uma técnica estatística usada para <b>modelar a relação entre uma variável dependente (alvo)</b> e <b>uma ou mais variáveis independentes (preditoras)</b>. Ela é amplamente usada para <b>previsão de valores</b> e <b>análise de impacto de variáveis</b>.</p>

>### 📌 <b>Por que se chama _Regressão Linear_?</b>

- **Regressão** significa que estamos tentando **prever ou estimar** um valor com base em outros dados.  
  Por exemplo: prever o **preço de uma casa** com base na **área**, **distância da praia** e **distância da farmácia**.

- **Linear** vem do fato de que a relação entre as variáveis é representada por uma **linha reta**.  
  Ou seja, o modelo tenta ajustar uma **equação do tipo**:    


<div align="center">
  <img src='https://i.postimg.cc/XY9PvyNz/formula.png'>
</div>


Onde:

- <i>Valor</i> é a variável dependente (o que queremos prever).

- <i>Area, Dist_Praia, Dist_Farmacia</i> são as variáveis independentes.

- 𝑎, 𝑏, 𝑐  são os coeficientes que indicam o impacto de cada variável.

- 𝑑  é o intercepto (valor base quando todas as variáveis são zero).

---

> ### 📝 <b>Em resumo:</b>
> É chamada de **regressão linear** porque usamos uma **equação de linha reta** para **estimar ou prever** valores com base em outras variáveis.

>### 🏠 <b>Projeto Prático: previsão de preços de casas</b>   

O objetivo do projeto é <b>prever o preço de casas</b> com base em:

- Área construída (Area)

- Distância da praia (Dist_Praia)

- Distância da farmácia (Dist_Farmacia)

>### 📥<b> Preparação do ambiente</b>
"""

# EXECUTE!
# Importações de bibliotecas Python
import pandas as pd  # Manipulação de dados
import statsmodels.api as sm  # Modelo estatístico
from sklearn.model_selection import train_test_split  # Divide dados em treino e teste
from sklearn.linear_model import LinearRegression     # Modelo de regressão linear

""">### ⬆️<b> Upload dos dados</b>  
- SALVE NO COMPUTADOR uma cópia do arquivo [dataset-imoveis.csv](https://drive.google.com/file/d/1AP9N7g0ZGBmf2nej-cQ37oo216Cs8-oM/view?usp=sharing).
- Clique no ícone de pasta no lado esquerdo e na folha com seta.  
- Selecione o arquivo <b>dataset-imoveis.csv</b> no computador.  
- Será exibida mensagem sobre exclusão dos arquivos ao encerrar o ambiente de execução, clique em OK e aguarde concluir.
"""

# EXECUTE!
# Carregar dataset
data = pd.read_csv('/content/dataset-imoveis.csv', sep=';')
data    # Exibe o conjunto de dados

""">### 📊 <b>Aplicação com Statsmodels</b>    

 🔗 Código 1 disponível [aqui](https://docs.google.com/document/d/12k7WwgomCIDMoFKsnE-s-ykr3eLOuFD-raqits_fJI0/edit?usp=sharing).   

 <img src='https://i.postimg.cc/0jKXm6vK/codigo-ASTATs.png'>

>### 🧪 <b>Aplicação com Scikit-Learn</b>    

🔗 Código 2 disponível [aqui](https://docs.google.com/document/d/1M7E5S-ITlXVmLuIZMvpi2z-X9LUVhk7MKn0hI3kmN4o/edit?usp=sharing).

<img src='https://i.postimg.cc/05Z7d5jf/modelo2SCIKIT.png'>

> ### 📌 <b>CONCEITOS IMPORTANTES</b>

>🔹 <b>Intercepto</b>  

<b>- Statsmodels</b>: O intercepto precisa ser adicionado manualmente com <i>sm.add_constant(X)</i>.   
Aparece como <i>const</i> no resumo estatístico.  

<b>- Scikit-Learn</b>: O intercepto é incluído automaticamente.  
Pode ser acessado com <i>model.intercept_</i>.

>🔹 <b>Coeficientes</b>      

<b>- Statsmodels</b>: Os coeficientes aparecem no <i>summary()</i> com seus respectivos p-valores, indicando a significância estatística de cada variável.  

<b>- Scikit-Learn</b>: Os coeficientes são acessados com <i>model.coef_</i>, mas não incluem p-valores ou testes estatísticos.

>🔹 <b>Métricas estatísticas comparadas</b>

| Métrica         | `statsmodels`                          | `scikit-learn`                     |
|-----------------|----------------------------------------|------------------------------------|
| R² (score)      | Incluído no `summary()`                | `model.score()`                    |
| p-valores       | Sim, para cada variável                | Não disponível                     |
| F-statistic     | Sim, avalia o modelo como um todo      | Não disponível                     |
| Intercepto      | `const` no `summary()`                 | `model.intercept_`                |

>### ⚖️<b>Comparação entre `statsmodels` e `scikit-learn`</b>  
>  

| Aspecto                     | `statsmodels`                          | `scikit-learn`                        |
|----------------------------|----------------------------------------|--------------------------------------|
| 📦 Foco principal           | Estatística clássica                   | Machine Learning                     |
| 🔍 Saída de resultados      | Resumo estatístico completo            | Apenas coeficientes e previsões      |
| 🧠 Ideal para               | Interpretação e análise profunda       | Previsão e integração com ML         |
| 📈 Intercepto               | Requer `add_constant()`                | Adicionado automaticamente           |
| 📊 Métricas estatísticas    | Detalhadas (p-valores, F-stat, etc.)   | Limitadas (R²)                       |

>###  🏁 <b>Testes no Google Colab</b>  
>
>- Copie e cole os códigos acima em células separadas.
>
>- Execute célula por célula para visualizar os resultados.

>📊 <b>Teste da aplicação com Statsmodels</b>
"""

# [Regressão Linear 1: código com Statsmodels]
# MODELO STATSMODELS
# Selecionar variáveis
X = data[['Area', 'Dist_Praia', 'Dist_Farmacia']]
y = data['Valor']


# Adicionar constante (intercepto)
X = sm.add_constant(X)


# Criar e ajustar o modelo
model = sm.OLS(y, X).fit()


# Exibir resumo estatístico
print(model.summary())

""">🧪 <b>Teste da aplicação com Scikit-Learn</b>"""

# [Regressão Linear 2: código com Scikit-Learn]

# MODELO SCIKIT-LEARN
# Selecionar variáveis
X = data[['Area', 'Dist_Praia', 'Dist_Farmacia']]   # Variáveis independentes (preditoras)
y = data['Valor']   # Variável dependente (alvo)


# Dividir em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Criar e treinar o modelo
model = LinearRegression()
model.fit(X_train, y_train)


# Exibir coeficientes
print("Coeficientes:", model.coef_)
print("Intercepto:", model.intercept_)
print("R² (score):", model.score(X_test, y_test))

""">### 📚 <b>Conclusão da aula</b>  
>
>- Aprendemos a aplicar regressão linear com duas bibliotecas diferentes.
>
>- Entendemos o papel dos coeficientes e do intercepto.
>
>- Exploramos métricas para avaliar o modelo.
>
>- Vimos como usar o Google Colab para testar os códigos.

###### 💻 <i>Nobebook elaborado pela profª Carla Silveira em 11/11/2025.</i>
"""